Feat font types
interglobalvision/despachodurango-net pull request #8
Opened 2017-02-25 00:56 UTC by mixcas

plz check if my font sizes are right ;3

2017-02-27 19:56 UTC, mikeyrayvon commented
how did you determine these rem font sizes @mixcas ? i really believe we should use px. I dont see the benefit of using em or rem at all.

2017-02-27 20:01 UTC, varffs requested changes
This wasn't the suggestion I meant. The way it is done in Pindrop is very different. The point of the rems is to set them in the font-sizes() mixin based on the base size. The boilerplate seems to be out of date related to how we have done type for a few projects

2017-02-27 20:01 UTC, varffs commented on css/site.styl
> +@import 'fonts/Din/Din'
include the font files first before type

2017-02-27 20:01 UTC, varffs commented on css/site.styl
> +  font-family: 'Din'
then use a font stack here and a variable `$font-sans` etc here

2017-02-27 20:01 UTC, varffs commented on css/site.styl
> +  font-family: 'Din'
also this declaration should be in type.styl

2017-02-27 20:16 UTC, mikeyrayvon commented
I really disagree with the way its done in pindrop. Type sizes should not be locked to fixed ratios. As the ration between type sizes often changes across viewports. Ex: Basic and small fonts are both be 14px in mobile, and are 16 and 14px in tablet, for the sake of legibility. I believe we should redeclare font sizes in px with mixin for each media query

2017-02-27 20:19 UTC, varffs commented
Read the Pindrop file. There is a modulator with minimum sizes. It might not be a good way to do it but they've not asked for any typesize changes on Pindrop for responsive since I added modulation. That made it a drop in solution that very quickly did responsive type sizes, I just had to tweak the modulator setting a little bit by eye. It seems a nice way to scale things down without losing the size relationships. However I concede that it is quite a complex way of doing things and would certainly either need an override or maybe not be at a good way at all.

2017-02-28 00:47 UTC, varffs commented
I think we should move to 1 of 2 approaches for font styles. 

We can either keep down this route with the mixin, but make the adjustments we decided on i.e. removing mapping of sizes to tags so no `$font-size-h1` set manually to an `h3` because thats the designs. If we are using mixin approach then I favor and like the modulator as it is a very rapid way to have a mobile type size setup that works.

The other approach is to move away from the mixin for sizes and map out all the different font styles used in a design. Then all these styles are declared as mapped to classes and all the markup is reset (other than the base HTML declaration) And we just have to remember to redeclare as needed on the responsive breakpoints. Once we start doing mobile first properly this will be cleaner than it is now.

Advantage of first is speed once configured, advantage of second is more fine tune customization as well as less duplicate and unneeded generated css.

I think I would advocate having a quality mixin in the boiler that we can use to prototype or one certain projects, but that we should move towards the second option in the future. The first step of the second option is to fix the mobile first approach

2017-02-28 18:36 UTC, varffs requested changes

2017-02-28 18:36 UTC, varffs commented on css/type.styl
> +  .font-large
I think these should be `.font-size-large` etc

2017-02-28 18:36 UTC, varffs commented on page-info.php
> +          <h2 class="font-heading font-uppercase font-size-heading">About</h2>
Its kinda annoying that `.font-heading` is so close to the size class. I wonder if it should be `.font-family-heading` or `.font-typeface-heading` or `.font-file-heading` ?

2017-02-28 19:10 UTC, mixcas commented
I decided to go with the modulator mixing approach for now since we don't have mobile designs yet.

Maybe we should improve the starter-pack on this part, let's do it when @mikeyrayvon gets back.

2017-02-28 19:27 UTC, mixcas commented on page-info.php
> +          <h2 class="font-heading font-uppercase font-size-heading">About</h2>
imma fix it to `.font-family-din`

2017-02-28 19:28 UTC, mixcas commented on page-info.php
> +          <h2 class="font-heading font-uppercase font-size-heading">About</h2>
ugh, nvm i stopped like it

2017-02-28 19:46 UTC, varffs commented on css/type.styl
> +  .font-large
@mixcas and this?

2017-03-02 17:43 UTC, mikeyrayvon commented
My feeling is that the mixin should be configured to never or almost never be modified between projects. I fear that the modulator approach youre using now will almost always need to be modified in the mixin. because the else condition of `basic + 1` just doesnt work for every project (or even any project?). what is the use case proof for this approach? The mixin that is defined in the static starter pack would allow for either modulator or px perfect font size class declarations. but you would do the math in the query instead of the mixin.  i think thats more flexible / future proof

2017-03-02 18:40 UTC, varffs approved these changes

2017-03-02 18:52 UTC, varffs commented
I see your point Mikey but for the sake of this nightmare PR I'm just going to merge it. The classes we are using are correct so we can refactor the stylus later esp if we get a different design for mobile or whatever. Also think we should do a full stylus refactor for the starter pack soon

2017-03-02 18:53 UTC, merged